# Generated by Django 5.2.3 on 2025-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_link',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
