# Generated by Django 5.2.3 on 2025-06-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_course_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
